version: '3'

services:
  vector:
    image: timberio/vector:0.22.2-debian
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - ./logs:/opt/logs:ro
    ports:
      - 8383:8383
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb2
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb2
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxdb
      - DOCKER_INFLUXDB_INIT_ORG=etalab
      - DOCKER_INFLUXDB_INIT_BUCKET=vector-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=A2jqhzcRPZeT3bAF
