# -- LOG STRAGEGY (vs metrics strategy) --
# So, this ain't pretty 😅
# Alternatives:
# - cleanup from scratch (ie not capture groups)
# - use `only_fields` but it doesnt exist anymore 😭
# - use log to metrics conversion (but this does not seem apt re our usecase)
#   -> see below, works pretty well
# [transforms.cleanup_message]
# type = "remap"
# inputs = ["map_to_resource"]
# source = '''
# del(.accept_date) # "12/Jun/2022:00:00:42.629",
# del(.act) # "759",
# del(.appname) # "haproxy",
# del(.backend_name) # "DATAGOUVFR_NEWINFRA",
# del(.be) # "5",
# del(.bytes_read) # "+925",
# del(.client_port) # "56940",
# del(.fe) # "742",
# del(.frontend_name) # "DATAGOUVFR_RGS~",
# del(.hostname) # "slb-04",
# del(.http_request) # "GET /fr/datasets/r/3a908e66-2d33-4cb8-8ce1-66a7a46950a4 HTTP/1.1",
# del(.message) # "47.187.205.185:56940 [12/Jun/2022:00:00:42.629] DATAGOUVFR_RGS~ DATAGOUVFR_NEWINFRA/dataweb-05 0/0/1/14/+15 302 +925 - - --NN 759/742/5/2/0 0/0 \"GET /fr/datasets/r/3a908e66-2d33-4cb8-8ce1-66a7a46950a4 HTTP/1.1\"",
# del(.procid) # 3103325,
# del(.protocol) # "HTTP/1.1"
# del(.queue_backend) # "0",
# del(.queue_server) # "0",
# del(.retries) # "0",
# del(.srv) # "2",
# del(.tc) # "1",
# del(.tq) # "0",
# del(.tr) # "14",
# del(.tt) # "+15",
# del(.tw) # "0"
# '''

# [sinks.out]
# type = "console"
# inputs = [ "cleanup_message" ]
#   [sinks.out.encoding]
#   codec = "json"

# -- LOG STRAGEGY (vs metrics strategy) --
# [sinks.influxdb_logs]
# type = "influxdb_logs"
# inputs = [ "cleanup_message" ]
# bucket = "vector-bucket"
# endpoint = "http://influxdb:8086/"
# org = "etalab"
# token = "A2jqhzcRPZeT3bAF"
# measurement = "vector-logs"