[enrichment_tables.organizations]
type = "file"
[enrichment_tables.organizations.file]
encoding = { type = "csv", delimiter = ";" }
path = "/opt/tables/organizations.csv"

[transforms.map_to_organization]
type = "remap"
inputs = [ "route_by_type.organization" ]
source = '''
url = join!(["http://www.data.gouv.fr/fr/organizations/", .organization_name, "/"])
row = get_enrichment_table_record("organizations", {"url": url}) ?? {}
.organization_id = get(row, ["id"]) ?? null
'''

[transforms.metric_count_organizations]
type = "log_to_metric"
inputs = [ "map_to_organization" ]

  [[transforms.metric_count_organizations.metrics]]
  field = "organization_id"
  namespace = "organization"
  type = "counter"

    [transforms.metric_count_organizations.metrics.tags]
    organization_id = "{{organization_id}}"
    request_api = "{{request_api}}"
    method = "{{method}}"
    status_code = "{{status_code}}"
